import * as React from "react";
import { DataGrid } from "@mui/x-data-grid";

const columns = [
  { field: "id", headerName: "ID", width: 50 },
  { field: "description", headerName: "Descripción", width: 350 },
  { field: "stock", headerName: "Stock", width: 70 },
  { field: "rubro", headerName: "Rubro", width: 130 },
  { field: "subRubro", headerName: "Sub-rubro", width: 130 },
  { field: "active", headerName: "Activo", width: 70, type: "boolean" },
];

const rows = [
  {
    id: 1,
    description: "Martillo de carpintero",
    stock: 50,
    rubro: "Herramientas",
    subRubro: "Martillos",
    active: true,
  },
  {
    id: 2,
    description: "Destornillador Phillips",
    stock: 40,
    rubro: "Herramientas",
    subRubro: "Destornilladores",
    active: true,
  },
  {
    id: 3,
    description: "Tornillo de acero inoxidable",
    stock: 500,
    rubro: "Fijaciones",
    subRubro: "Tornillería",
    active: true,
  },
  {
    id: 4,
    description: "Cinta métrica de 5 metros",
    stock: 30,
    rubro: "Herramientas de medición",
    subRubro: "Cintas métricas",
    active: true,
  },
  {
    id: 5,
    description: "Llave ajustable de 10 pulgadas",
    stock: 20,
    rubro: "Herramientas",
    subRubro: "Llaves",
    active: true,
  },
  {
    id: 6,
    description: "Pintura para interiores blanco mate",
    stock: 100,
    rubro: "Pinturas",
    subRubro: "Pinturas para interiores",
    active: true,
  },
  {
    id: 7,
    description: "Taladro eléctrico de 500W",
    stock: 15,
    rubro: "Herramientas eléctricas",
    subRubro: "Taladros",
    active: true,
  },
  {
    id: 8,
    description: "Clavo de acero galvanizado 2 pulgadas",
    stock: 800,
    rubro: "Fijaciones",
    subRubro: "Clavos",
    active: true,
  },
  {
    id: 9,
    description: "Sierra de mano para madera",
    stock: 25,
    rubro: "Herramientas",
    subRubro: "Sierras",
    active: true,
  },
  {
    id: 10,
    description: "Tubo de PVC de 3 metros",
    stock: 50,
    rubro: "Fontanería",
    subRubro: "Tubos",
    active: true,
  },
  {
    id: 11,
    description: "Guantes de trabajo",
    stock: 60,
    rubro: "Equipo de protección personal",
    subRubro: "Guantes",
    active: true,
  },
  {
    id: 12,
    description: "Pala de jardín",
    stock: 35,
    rubro: "Herramientas de jardinería",
    subRubro: "Palas",
    active: true,
  },
  {
    id: 13,
    description: "Llave hexagonal juego de 9 piezas",
    stock: 10,
    rubro: "Herramientas",
    subRubro: "Llaves",
    active: true,
  },
  {
    id: 14,
    description: "Cerradura de puerta",
    stock: 30,
    rubro: "Ferretería",
    subRubro: "Cerraduras",
    active: true,
  },
  {
    id: 15,
    description: "Cepillo metálico para limpieza",
    stock: 40,
    rubro: "Herramientas de limpieza",
    subRubro: "Cepillos",
    active: true,
  },
  {
    id: 16,
    description: "Bisagra para puerta de madera",
    stock: 50,
    rubro: "Ferretería",
    subRubro: "Bisagras",
    active: true,
  },
  {
    id: 17,
    description: "Talocha de albañil",
    stock: 20,
    rubro: "Herramientas de construcción",
    subRubro: "Talochas",
    active: true,
  },
  {
    id: 18,
    description: "Grifo de cocina",
    stock: 25,
    rubro: "Fontanería",
    subRubro: "Grifos",
    active: true,
  },
  {
    id: 19,
    description: "Alicate de corte",
    stock: 30,
    rubro: "Herramientas",
    subRubro: "Alicates",
    active: true,
  },
  {
    id: 20,
    description: "Tornillo para madera cabeza avellanada",
    stock: 500,
    rubro: "Fijaciones",
    subRubro: "Tornillería",
    active: true,
  },
  {
    id: 21,
    description: "Flexómetro de 3 metros",
    stock: 40,
    rubro: "Herramientas de medición",
    subRubro: "Flexómetros",
    active: true,
  },
  {
    id: 22,
    description: "Candado de seguridad",
    stock: 15,
    rubro: "Ferretería",
    subRubro: "Candados",
    active: true,
  },
  {
    id: 23,
    description: "Serrucho de carpintero",
    stock: 20,
    rubro: "Herramientas",
    subRubro: "Sierras",
    active: true,
  },
  {
    id: 24,
    description: "Cinta de aislar eléctrica",
    stock: 50,
    rubro: "Electricidad",
    subRubro: "Cintas aislantes",
    active: true,
  },
  {
    id: 25,
    description: "Escalera de aluminio de 6 peldaños",
    stock: 10,
    rubro: "Herramientas de acceso",
    subRubro: "Escaleras",
    active: true,
  },
  {
    id: 26,
    description: "Broca para madera de 6 mm",
    stock: 100,
    rubro: "Herramientas de corte",
    subRubro: "Brocas",
    active: true,
  },
  {
    id: 27,
    description: "Llave de tubo de 8 pulgadas",
    stock: 25,
    rubro: "Herramientas",
    subRubro: "Llaves",
    active: true,
  },
  {
    id: 28,
    description: "Tirafondo para madera",
    stock: 400,
    rubro: "Fijaciones",
    subRubro: "Tornillería",
    active: true,
  },
  {
    id: 29,
    description: "Pintura para exteriores color rojo",
    stock: 80,
    rubro: "Pinturas",
    subRubro: "Pinturas para exteriores",
    active: true,
  },
  {
    id: 30,
    description: "Llave de vaso de 13 mm",
    stock: 30,
    rubro: "Herramientas",
    subRubro: "Llaves",
    active: true,
  },
];

export default function DataTable() {
  return (
    <DataGrid
      rows={rows}
      columns={columns}
      initialState={{
        pagination: {
          paginationModel: { page: 0, pageSize: 10 },
        },
      }}
      pageSizeOptions={[5, 10]}
    />
  );
}
